"""Service to communicate with the Gemini API over HTTP."""

import logging
from typing import Any, Dict, List, Optional
import httpx

from backend.config import settings

logger = logging.getLogger(__name__)


class GeminiService:
    """Handles communication with the Gemini API using HTTP client."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.GEMINI_API_KEY
        self.model = "gemini-2.5-flash"
        self.base_url = "https://generativelanguage.googleapis.com/v1beta"

    async def generate_content(
        self,
        contents: List[Dict[str, Any]],
        system_instruction: Optional[str] = None,
        temperature: float = 0.2
    ) -> str:
        """
        Calls Gemini API generateContent endpoint.
        contents: List of message dicts matching Gemini API schema, e.g.:
          [{"role": "user", "parts": [{"text": "hello"}]}]
        """
        if not self.api_key:
            logger.error("Gemini API key is not configured.")
            return "Error: Gemini API Key is missing. Please set GEMINI_API_KEY in your environment configuration."

        url = f"{self.base_url}/models/{self.model}:generateContent?key={self.api_key}"

        payload: Dict[str, Any] = {
            "contents": contents,
            "generationConfig": {
                "temperature": temperature
            }
        }

        if system_instruction:
            payload["systemInstruction"] = {
                "parts": [
                    {"text": system_instruction}
                ]
            }

        headers = {
            "Content-Type": "application/json"
        }

        try:
            async with httpx.AsyncClient(timeout=httpx.Timeout(30.0, connect=10.0)) as client:
                response = await client.post(url, json=payload, headers=headers)
                
                if response.status_code != 200:
                    logger.error(f"Gemini API returned status {response.status_code}: {response.text}")
                    try:
                        err_json = response.json()
                        error_msg = err_json.get("error", {}).get("message", "Unknown error")
                        return f"Error from Gemini API: {error_msg}"
                    except Exception:
                        return f"Error: Gemini API returned HTTP status {response.status_code}."

                res_data = response.json()
                
                # Extract response text
                candidates = res_data.get("candidates", [])
                if not candidates:
                    logger.warning(f"Gemini API returned no candidates: {res_data}")
                    return "Error: No response generated by Gemini."
                
                parts = candidates[0].get("content", {}).get("parts", [])
                if not parts:
                    logger.warning(f"Gemini API response candidate has no parts: {res_data}")
                    return "Error: Empty response candidate parts from Gemini."

                return parts[0].get("text", "")

        except httpx.TimeoutException:
            logger.error("Request to Gemini API timed out.")
            return "Error: Connection timed out while contacting Gemini API."
        except Exception as e:
            logger.exception("Unexpected error calling Gemini API:")
            return f"Error: An unexpected error occurred: {str(e)}"


gemini_service = GeminiService()
